// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MovieExpert_Proiect
{
    public partial class MovieRecommender
    {
        /// <summary>
        /// model input class for MovieRecommender.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(2)]
            [ColumnName(@"Released_Year")]
            public string Released_Year { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"Runtime")]
            public string Runtime { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"Genre")]
            public string Genre { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"IMDB_Rating")]
            public float IMDB_Rating { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"Director")]
            public string Director { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"Star1")]
            public string Star1 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MovieRecommender.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Released_Year")]
            public float[] Released_Year { get; set; }

            [ColumnName(@"Runtime")]
            public float[] Runtime { get; set; }

            [ColumnName(@"Genre")]
            public float[] Genre { get; set; }

            [ColumnName(@"IMDB_Rating")]
            public float IMDB_Rating { get; set; }

            [ColumnName(@"Director")]
            public float[] Director { get; set; }

            [ColumnName(@"Star1")]
            public float[] Star1 { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MovieRecommender.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
